name: Deploy Telegram Bot to Beget

on:
  push:
    branches:
      - main # Скрипт срабатывает каждый раз, когда вы делаете push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and Build Frontend
        run: |
          npm install
          npm run build # Сборка вашего Mini App (создает актуальную папку dist)

      - name: Sync files to Beget via SSH/rsync
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts
          sudo apt-get install -y sshpass rsync
          sshpass -e rsync -avz --exclude='.git/' --exclude='node_modules/' --exclude='.env' --exclude='bin/' --exclude='tmp/' ./ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/home/p/platines/bot-solien/

      - name: Restart Node.js Server on Beget via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/p/platines/bot-solien
            mkdir -p tmp
            touch tmp/restart.txt