name: Deploy Telegram Bot to Beget

on:
  push:
    branches:
      - main # Скрипт срабатывает каждый раз, когда вы делаете push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and Build Frontend
        run: |
          npm install
          npm run build # Сборка вашего Mini App (создает актуальную папку dist)

      - name: Sync files to Beget via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: / # Загрузка идет строго в корень домена, а не в public_html
          exclude: |
            **/.git*
            **/node_modules/**
            **/.env
            **/bin/**
            **/tmp/**

      - name: Restart Node.js Server on Beget via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd ~/bot-solien
            npm install --production # Обновляем модули на сервере, если в package.json появились новые
            touch tmp/restart.txt # Даем команду Passenger перезапустить бота с новым кодом